spring:
  datasource:    url: jdbc:postgresql://localhost_5432/postgres
    username: postgres
    password: platzi
    driver-class-name: org.postgres.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    show-sql: true